### ISSUE TITLE
create frontend subproject

### ISSUE THREAD

**Issue by jbuddha** [coderplex/OpenRank#18]

**Comment by vinaypuppal** [comment]
Hi @jbuddha ,
I have a suggestion regarding frontend, consider using [Nuxt.js](https://nuxtjs.org/) which is **Universal Vue.js Framework**
## Why?
Because of less config
-  Filesystem as router
- automatic code splitting per route
- default server side rendering(but can be changed to [SPA mode with config's](https://nuxtjs.org/guide/commands#production-deployment))
- And finally it has many [Official modules](https://github.com/nuxt-community/modules) which can be integrated easily without much configuration.

Read about more features [here](https://nuxtjs.org/guide)

**Comment by vinaypuppal** [comment]
And for the vuejs css framework you can consider [vuetifyjs](https://vuetifyjs.com/) as it has wide range of components.
(If material design is okay for this application)
